#ifndef TWI_LCD_PRIVATE_H_
#define TWI_LCD_PRIVATE_H_

#define LCD_CLR  0X01
#define LCD_CURSOR_FIRST_LINE 0X80
#define LCD_4BIT_MODE 0x28
#define LCD_8BIT_MODE 0x38
#define LCD_CURSOR_ON 0x0c
#define LCD_DISPLAY_ON_CURSOR_OFF 0x0C
#define LCD_DISPLAY_OFF_CURSOR_OFF 0X08
#define LCD_DISPLAY_ON_CURSOR_ON 0X0E
#define LCD_DISPLAY_OFF_CURSOR_ON 0X0A
#define CURSOR_BLINK 0X0F
#define LCD_CURSOR_SEC_LINE 0XC0
#define LCD_SHIFT_LEFT 0X07
#define LCD_SHIFT_RIGHT 0X05
#define LCD_CURSOR_SHIFT_RIGHT 0X06
#define LCD_CURSOR_SHIFT_LIFT 0X04
#define RETURN_HOME 0X02




#endif /* TWI_LCD_PRIVATE_H_ */
