
/**********************************************************************/
/**************** @ AUTHOR : Abdullah waheed  @ ***********************/
/**************** @ DATE   : 26 - 9 - 2023    @ ***********************/
/**************** @ FILE   : SSD_PROGRAM.C    @ ***********************/
/**************** @ BRIEF  : SRC CODE         @ ***********************/
/**********************************************************************/

#include "HAL/SSD/SSD_INTERFACE.h"
#include "HAL/SSD/SSD_PRTIVATE.h"

uint8 SSD_NUM[] = SSD_NUMBER_ARR ;

SSD_ERROR_TYPE SSD_ENUM_INIT(SSD_CONFIG CONFIG) 
{
	SSD_ERROR_TYPE STATUS = SSD_OK ;
	if ( CONFIG.DATA_PORT <= PORTD && CONFIG.ENABLE_PORT <= PORTD  && CONFIG.TYPE <= COMMON_CATHODE)
	{
		DIO_ENUM_SET_PIN_DIR(CONFIG.DATA_PORT,CONFIG.PIN_A,OUTPUT);
		DIO_ENUM_SET_PIN_DIR(CONFIG.DATA_PORT,CONFIG.PIN_B,OUTPUT);
		DIO_ENUM_SET_PIN_DIR(CONFIG.DATA_PORT,CONFIG.PIN_C,OUTPUT);
		DIO_ENUM_SET_PIN_DIR(CONFIG.DATA_PORT,CONFIG.PIN_D,OUTPUT);
		DIO_ENUM_SET_PIN_DIR(CONFIG.DATA_PORT,CONFIG.PIN_E,OUTPUT);
		DIO_ENUM_SET_PIN_DIR(CONFIG.DATA_PORT,CONFIG.PIN_F,OUTPUT);
		DIO_ENUM_SET_PIN_DIR(CONFIG.DATA_PORT,CONFIG.PIN_G,OUTPUT);
		DIO_ENUM_SET_PIN_DIR(CONFIG.ENABLE_PORT,CONFIG.PIN_EN,OUTPUT);
	}
	else
	{
		STATUS = SSD_NOK ;
	}
	return STATUS ;
}

SSD_ERROR_TYPE SSD_ENUM_SEND_DATA(SSD_CONFIG CONFIG , uint8 NUM) 
{
	SSD_ERROR_TYPE STATUS = SSD_OK ;
	if ( CONFIG.DATA_PORT <= PORTD && CONFIG.ENABLE_PORT <= PORTD  && CONFIG.TYPE <= COMMON_CATHODE)
	{
		switch(CONFIG.TYPE)
		{
			case  COMMON_ANODE : 
			{
				
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_A,BIT_GET(~SSD_NUM[NUM],0));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_B,BIT_GET(~SSD_NUM[NUM],1));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_C,BIT_GET(~SSD_NUM[NUM],2));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_D,BIT_GET(~SSD_NUM[NUM],3));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_E,BIT_GET(~SSD_NUM[NUM],4));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_F,BIT_GET(~SSD_NUM[NUM],5));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_G,BIT_GET(~SSD_NUM[NUM],6));
				break ;
			}
			case  COMMON_CATHODE : 
			{
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_A,BIT_GET(SSD_NUM[NUM],0));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_B,BIT_GET(SSD_NUM[NUM],1));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_C,BIT_GET(SSD_NUM[NUM],2));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_D,BIT_GET(SSD_NUM[NUM],3));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_E,BIT_GET(SSD_NUM[NUM],4));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_F,BIT_GET(SSD_NUM[NUM],5));
				DIO_ENUM_SET_PIN_VAL(CONFIG.DATA_PORT,CONFIG.PIN_G,BIT_GET(SSD_NUM[NUM],6));
				break;
			}
		}
	}
	else
	{
		STATUS = SSD_NOK ;
	}
	return STATUS ;
}

SSD_ERROR_TYPE SSD_ENUM_ENABLE(SSD_CONFIG CONFIG) 
{
	SSD_ERROR_TYPE STATUS = SSD_OK ;
	if ( CONFIG.DATA_PORT <= PORTD && CONFIG.ENABLE_PORT <= PORTD  && CONFIG.TYPE <= COMMON_CATHODE)
	{
		switch(CONFIG.TYPE)
		{
			case  COMMON_ANODE :
			{
				DIO_ENUM_SET_PIN_VAL(CONFIG.ENABLE_PORT,CONFIG.PIN_EN,HIGH) ;
				break ;
			}
			case  COMMON_CATHODE :
			{
				DIO_ENUM_SET_PIN_VAL(CONFIG.ENABLE_PORT,CONFIG.PIN_EN,LOW) ;
				break;
			}
		}
	}
	else
	{
		STATUS = SSD_NOK ;
	}
	return STATUS ;
}

SSD_ERROR_TYPE SSD_ENUM_DISABLE(SSD_CONFIG CONFIG) 
{
	SSD_ERROR_TYPE STATUS = SSD_OK ;
	if ( CONFIG.DATA_PORT <= PORTD && CONFIG.ENABLE_PORT <= PORTD  && CONFIG.TYPE <= COMMON_CATHODE)
	{
		switch(CONFIG.TYPE)
		{
			case  COMMON_ANODE :
			{
				DIO_ENUM_SET_PIN_VAL(CONFIG.ENABLE_PORT,CONFIG.PIN_EN,LOW) ;
				break ;
			}
			case  COMMON_CATHODE :
			{
				DIO_ENUM_SET_PIN_VAL(CONFIG.ENABLE_PORT,CONFIG.PIN_EN,HIGH) ;
				break;
			}
		}
	}
	else
	{
		STATUS = SSD_NOK ;
	}
	return STATUS ;
}



